export const SET_TRANSPORT = 'SET_TRANSPORT';
export const FETCH_TRANSPORT_FAILED = 'FETCH_TRANSPORT_FAILED';
export const SET_TRANSPORT_PROVIDER = 'SET_TRANSPORT_PROVIDER';
export const FETCH_TRANSPORT_PROVIDER_FAILED = 'FETCH_TRANSPORT_PROVIDER_FAILED';
export const SET_TRANSPORT_VEHICLE_TYPE_FILTER = 'SET_TRANSPORT_VEHICLE_TYPE_FILTER';
export const SET_TRANSPORT_PRICE_PER_DAY_FILTER_02 = 'SET_TRANSPORT_PRICE_PER_DAY_FILTER_02';
export const SET_TRANSPORT_PRICE_PER_DISTANCE_FILTER_03 = 'SET_TRANSPORT_PRICE_PER_DISTANCE_FILTER_03';
export const SET_TRANSPORT_INPUT_FORM = 'SET_TRANSPORT_INPUT_FORM';
export const GET_TRANSPORT_INPUT_FORM = 'GET_TRANSPORT_INPUT_FORM';
export const GET_GUIDE_INPUT_FORM = 'GET_GUIDE_INPUT_FORM';
export const GET_TRANSPORT_IMAGE_URL = 'GET_TRANSPORT_IMAGE_URL';


export const SET_GUIDE_LANGUAGE_TYPE_FILTER = 'SET_GUIDE_LANGUAGE_TYPE_FILTER'; 
export const SET_GUIDE_PRICE_TYPE_FILTER = 'SET_GUIDE_PRICE_TYPE_FILTER';

export const AUTH_START = 'AUTH_START';  
export const AUTH_SUCCESS = 'AUTH_SUCCESS'; 
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_HOTEL_INPUT_FORM = 'GET_HOTEL_INPUT_FORM';
export const SET_HOTEL_DISTRICT_FILTER = 'SET_HOTEL_DISTRICT_FILTER';
export const SET_HOTEL_PRICE_FILTER = 'SET_HOTEL_PRICE_FILTER';
export const SET_HOTEL_PRICERANGE_FILTER = 'SET_HOTEL_PRICERANGE_FILTER';
export const SET_HOTEL_STARS_FILTER = 'SET_HOTEL_STARS_FILTER';
