export const SET_TRANSPORT = 'SET_TRANSPORT';
export const FETCH_TRANSPORT_FAILED = 'FETCH_TRANSPORT_FAILED';
export const SET_TRANSPORT_PROVIDER = 'SET_TRANSPORT_PROVIDER';
export const FETCH_TRANSPORT_PROVIDER_FAILED = 'FETCH_TRANSPORT_PROVIDER_FAILED';
export const SET_TRANSPORT_INPUT_FORM = 'SET_TRANSPORT_INPUT_FORM';
export const GET_TRANSPORT_INPUT_FORM = 'GET_TRANSPORT_INPUT_FORM';

